[package]
name = "excel-mysql-mover"
version = "0.1.0"
authors = ["Apetu Gideon <apetugideon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
office = "*"
calamine = "*"
mysql = "*"
chrono = "*"